#pragma once

extern "C" int   _stdcall Initialize(char* product);
extern "C" void  _stdcall Release();
extern "C" int   _stdcall Auth(char* serial);
extern "C" int   _stdcall UserAuth(char* acc, char* pwd);
extern "C" char* _stdcall Encrypt(BYTE type, char* src, char* key);
extern "C" char* _stdcall Decrypt(BYTE type, char* src, char* key);
extern "C" char* _stdcall GetCode();
extern "C" void  _stdcall Update(char* cmd);
extern "C" char* _stdcall GetBulletin();
extern "C" VARIANT_BOOL _stdcall IsValid();
extern "C" char*  _stdcall GetValidity();
extern "C" short  _stdcall DeductPoint(short point);
extern "C" USHORT _stdcall GetProductDataSize();
extern "C" BYTE   _stdcall GetProductData(USHORT pos);
extern "C" BYTE   _stdcall GetData(BYTE pos);
extern "C" int    _stdcall PutData(char* data);
extern "C" BYTE   _stdcall GetUserType();
extern "C" char*  _stdcall GetVer();
extern "C" int    _stdcall Unbind();
extern "C" int    _stdcall AddTime(char* card, char* buyer, char* super, SHORT* days, SHORT* point);
extern "C" int    _stdcall UserRegister(char* user, char* pwd, BYTE type, BYTE bind, BYTE multi, short point);
extern "C" int    _stdcall ChangePassword(char* Old, char* New);
extern "C" VARIANT_BOOL _stdcall IsConnected();
extern "C" char* _stdcall GetCurrTime();
extern "C" int   _stdcall DeductHour(DWORD hour);
extern "C" int   _stdcall GetTotalLen();
extern "C" int   _stdcall GetDownloadLen();
extern "C" void  _stdcall LeaveMsg(BYTE type, char* msg);
extern "C" void  _stdcall Rename(char* name);
extern "C" void  _stdcall InputMD5(BYTE* address, int len);
extern "C" void  _stdcall InputVNC(BYTE* address, int len);
